### PR TITLE
Add PiP methods

### LINKED ISSUE #351: Add hooks for Picture-in-Picture
It would be great to support the standardized Picture-in-Picture Web API and exposes some hooks when video enters and leaves Picture-in-Picture.

https://developers.google.com/web/updates/2018/10/watch-video-using-picture-in-picture
https://wicg.github.io/picture-in-picture/

### PR DESCRIPTION
**Pull request by luwes**
Adds the methods for picture-in-picture:

- `requestPictureInPicture()`
- `exitPictureInPicture()`

The events are added to the player core:

- `enterpictureinpicture`
- `leavepictureinpicture`

Fixes #351

### CODE REVIEW

**Comment by chinciusan** [comment]
Waiting for this 😄

**Review by chinciusan — APPROVED** [review]

**Comment by luwes** [comment]
thanks for the approval! this is not gonna make it in this week. probably next week! cheers

**Review by fisherinnovation — APPROVED** [review]
lgtm

**Comment by chinciusan** [comment]
hi! Do you think this will get in this week? 🤞

**Comment by luwes** [comment]
@chinciusan sorry, some other internal projects took priority this week. 
we're aiming to have it in before November.

**Comment by samirmh-dev** [comment]
Any progress on this feature?

**Comment by Nautman** [comment]
Is there anything I can help with? I am also waiting for this feature 🙌

**Pull request merged**
