### PR TITLE
update Readme.txt

### LINKED ISSUE #242: Chrome 66 prevents autoplay
### Expected Behavior
When using [the create video example](https://github.com/vimeo/player.js#create-with-a-video-id-or-url) prior to Chrome 66 auto play will work. 

### Actual Behavior
Autoplay fails to autoplay video due to the new [autoplay policy](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).

### Steps to Reproduce
Use [the create video example](https://github.com/vimeo/player.js#create-with-a-video-id-or-url) in Chrome 66 or later with the default policy

### Comment
Having the ability to override the policy is required as there is specific situations that autoplay is expected by the user

### PR DESCRIPTION
**Pull request by nextend**
Iframe must contain the allow attribute with autoplay; encrypted-media. If it is not there, Google Chrome's new autoplay policy does not work properly. https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

This attribute will allow to autoplay vimeo videos with sound.

Fixes #242.

### CODE REVIEW

**Comment by fisherinnovation** [comment]
Thanks for submitting the PR. However I don't think this is going to accomplish what you are expecting (example https://jsfiddle.net/eqh1gbf6/4/).
To control autoplay requests to the player you will need to pass an `autoplay` param (https://github.com/vimeo/player.js#embed-options). This of course is only a request, the browser will have the final say as to if this autoplay requests succeeds or not.

**Comment by nextend** [comment]
@fisherinnovation If autoplay param added to the embed options and these attributes what I suggested are not present the autoplay does not start with sound. This is why I suggested to add these attributes to the example. Or extends the readme.txt with an autoplay example. It would help a lot of people...

**Comment by luwes** [comment]
@nextend I don't understand, they are present in this fiddle and it's still not autoplaying with sound.
https://jsfiddle.net/eqh1gbf6/4/

It's still prevented by the browser, see this console log (not visible for you)
screen shot 2018-06-14 at 7 02 41 pm

**Comment by nextend** [comment]
@luwes You are testing it in the wrong environment as JSFiddle use iframe there with special context. Here are two test:

# Chrome
The following applies only if you already have click or touch interaction on the smartslider3.com domain. If a.html does not start click on the page anywhere and reload the page and the video will autoplay while b.html never will autoplay even we had the interaction

Contains allow="autoplay; encrypted-media" attribute and autoplays fine in Chrome:
https://smartslider3.com/bugs/vimeo/a.html

Vimeo readme.txt exmple, does not autoplay:
https://smartslider3.com/bugs/vimeo/b.html

**Comment by nextend** [comment]
Another two example with JavaScript. Open in private window (always use new private window, except I tell you to refresh the page), non of them will autoplay as Chrome does not allow it. Console will contain a message that 'Probably Google Chrome needs interaction to autoplay'. Click anywhere on the body, both video will start to autoplay. Then refresh the page, a1.html with the attributes will start to autoplay as Chrome knows the domain had an interaction in the past, a2.html will not autoplay until you click on the body again.

Contains allow="autoplay; encrypted-media" attribute:
https://smartslider3.com/bugs/vimeo/a1.html

Vimeo Readme.txt example:
https://smartslider3.com/bugs/vimeo/b1.html

**Comment by fisherinnovation** [comment]
Thanks for clearing that up @nextend!

**Comment by zwickmueller** [comment]
Hi, is there a way to do this workaround with "data-vimeo" attributes? I dont have existing Iframes in my project and need to load the videos conditional...

**Comment by danrossi** [comment]
@zwickmueller  confirmed the attribute isn't being included by the api.

**Pull request merged**
